# Generated by Django 4.2.2 on 2023-07-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_post_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resumen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
